### ISSUE TITLE
pigpio and pigpio-sys crates created

### ISSUE THREAD

**Issue by Kixunil** [rust-embedded/gpio-utils#25]
Hi, sorry for abusing this channel, I'm in hurry and want to get this out ASAP and don't have time for searching a better channel. I've created `pigpio` and `pigpio-sys` crates (published on crates.io). Feel free to try it out and help.

I can add someone from WG as maintainer if you're interested.

**Comment by nastevens** [comment]
Are there features present in pigpio that are missing from gpio-utils, sysfs-gpio, or cdev-gpio?

**Comment by Kixunil** [comment]
To my knowledge, at least wave generation is such a feature. (It uses DMA to do it.) That's also why I only bothered about implementing safe interface to generate waves.

Though, `pigpio` has quite awkward API, so I'm considering rewriting it (or the wave generation part) purely in Rust. It's not a priority to me, though.

**Comment by posborne** [comment]
For the embedded-linux part of the WG, I don't think we are too interested in directly maintaining crates that are not applicable across the Linux ecosystem.  Sounds like the pigpio is very specific to the bcm processor and is probably interacting with /dev/mem or similar.  There is of course nothing wrong with this for specific use cases but in general is not the encouraged way to interact with GPIOs unless one has specific requirements (as it sounds like you do for wave generation).

**Comment by Kixunil** [comment]
@posborne Fair enough. I'd be interested to know if there was a more generic way of generating waves (which I believe is quite widely used feature), but I don't think there's any right now.
